// peer_service/internal/media/m3u8_monitor.go
package media

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"log"
	"os"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/fsnotify/fsnotify"
)

var (
	extinfRegex        = regexp.MustCompile(`^#EXTINF:([0-9\.]+),`)
	segmentFileRegex   = regexp.MustCompile(`^[^#]+`) // Matches lines not starting with #
	mediaSequenceRegex = regexp.MustCompile(`^#EXT-X-MEDIA-SEQUENCE:(\d+)`)
)

// M3U8Monitor watches an M3U8 playlist file generated by ffmpeg and extracts
// segment durations.
type M3U8Monitor struct {
	playlistPath string
	mu           sync.RWMutex
	// Stores duration for segment by its sequence number relative to the start_number of ffmpeg
	segmentDurations map[uint32]float64
	currentMediaBase uint32 // Tracks #EXT-X-MEDIA-SEQUENCE from the playlist
	watcher          *fsnotify.Watcher
	ffmpegStartNum   uint32 // The -start_number ffmpeg was launched with
}

// NewM3U8Monitor creates a monitor for the given HLS playlist path.
// ffmpegStartNum is the -start_number option passed to the ffmpeg command that generates this playlist.
func NewM3U8Monitor(playlistPath string, ffmpegStartNum uint32) (*M3U8Monitor, error) {
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		return nil, fmt.Errorf("failed to create fsnotify watcher: %w", err)
	}

	m := &M3U8Monitor{
		playlistPath:     playlistPath,
		segmentDurations: make(map[uint32]float64),
		watcher:          watcher,
		ffmpegStartNum:   ffmpegStartNum,
		currentMediaBase: ffmpegStartNum, // Initialize with ffmpeg's start_number
	}

	// Initial parse
	if err := m.parsePlaylist(); err != nil {
		// Log error but continue, file might not exist yet or be empty
		log.Printf("M3U8Monitor: Initial parse of %s failed (might be normal if file not yet created): %v", playlistPath, err)
	}

	return m, nil
}

// Start begins watching the playlist file for changes.
func (m *M3U8Monitor) Start(ctx context.Context) {
	if err := m.watcher.Add(m.playlistPath); err != nil {
		// If the file doesn't exist yet, fsnotify might error.
		// We'll try to add it again after a short delay or on first write.
		// For now, log and proceed. Ffmpeg should create it soon.
		log.Printf("M3U8Monitor: Error adding %s to fsnotify watcher (will try to parse periodically): %v", m.playlistPath, err)
	}

	// Fallback polling ticker in case fsnotify has issues or initial add fails
	// (e.g. file doesn't exist when monitor starts)
	pollTicker := time.NewTicker(500 * time.Millisecond)
	defer pollTicker.Stop()

	go func() {
		defer m.watcher.Close()
		for {
			select {
			case <-ctx.Done():
				log.Printf("M3U8Monitor: Context done, stopping watcher for %s.", m.playlistPath)
				return
			case event, ok := <-m.watcher.Events:
				if !ok {
					log.Printf("M3U8Monitor: Watcher events channel closed for %s.", m.playlistPath)
					return
				}
				if event.Has(fsnotify.Write) || event.Has(fsnotify.Create) {
					// log.Printf("M3U8Monitor: Playlist %s modified (event: %s), parsing.", m.playlistPath, event.Op)
					if err := m.parsePlaylist(); err != nil {
						log.Printf("M3U8Monitor: Error parsing playlist %s on event: %v", m.playlistPath, err)
					}
					// If Create event, try to re-add to watcher in case previous add failed
					if event.Has(fsnotify.Create) {
						_ = m.watcher.Remove(m.playlistPath) // Just in case
						if err := m.watcher.Add(m.playlistPath); err != nil {
							log.Printf("M3U8Monitor: Error re-adding %s to watcher on create event: %v", m.playlistPath, err)
						} else {
							log.Printf("M3U8Monitor: Successfully re-added %s to watcher on create event.", m.playlistPath)
						}
					}
				}
			case err, ok := <-m.watcher.Errors:
				if !ok {
					log.Printf("M3U8Monitor: Watcher errors channel closed for %s.", m.playlistPath)
					return
				}
				log.Printf("M3U8Monitor: Watcher error for %s: %v", m.playlistPath, err)
			case <-pollTicker.C: // Polling fallback
				// log.Printf("M3U8Monitor: Polling playlist %s.", m.playlistPath)
				if _, err := os.Stat(m.playlistPath); err == nil { // File exists
					// Ensure it's being watched
					found := false
					for _, name := range m.watcher.WatchList() {
						if name == m.playlistPath {
							found = true
							break
						}
					}
					if !found {
						if errAdd := m.watcher.Add(m.playlistPath); errAdd != nil {
							log.Printf("M3U8Monitor (poll): Error adding %s to watcher: %v", m.playlistPath, errAdd)
						} else {
							log.Printf("M3U8Monitor (poll): Successfully added %s to watcher.", m.playlistPath)
						}
					}
					if err := m.parsePlaylist(); err != nil {
						log.Printf("M3U8Monitor (poll): Error parsing playlist %s: %v", m.playlistPath, err)
					}
				}
			}
		}
	}()
}

// Stop closes the watcher.
func (m *M3U8Monitor) Stop() {
	// Closing the watcher will cause its goroutine to exit.
	// No need to explicitly cancel context if Start takes one.
	m.watcher.Close()
}

func (m *M3U8Monitor) parsePlaylist() error {
	file, err := os.Open(m.playlistPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil // File not created yet, not an error for parsing
		}
		return fmt.Errorf("failed to open playlist file %s: %w", m.playlistPath, err)
	}
	defer file.Close()

	reader := bufio.NewReader(file)
	var currentExtInfDuration float64 = -1
	var latestMediaBase uint32 = m.ffmpegStartNum // Default to ffmpeg's start_number if not in playlist
	var segmentIndexInPlaylist int = 0            // 0-based index of segment *within the current playlist file*

	m.mu.Lock()
	defer m.mu.Unlock()

	tempDurations := make(map[uint32]float64) // Store new findings here

	for {
		line, err := reader.ReadString('\n')
		if err != nil && err != io.EOF {
			return fmt.Errorf("error reading playlist file %s: %w", m.playlistPath, err)
		}
		line = strings.TrimSpace(line)

		if match := mediaSequenceRegex.FindStringSubmatch(line); len(match) > 1 {
			seqVal, convErr := strconv.ParseUint(match[1], 10, 32)
			if convErr == nil {
				latestMediaBase = uint32(seqVal)
				// Reset segmentIndexInPlaylist because MEDIA-SEQUENCE applies to the *next* segment listed
				segmentIndexInPlaylist = 0
			}
		} else if match := extinfRegex.FindStringSubmatch(line); len(match) > 1 {
			duration, convErr := strconv.ParseFloat(match[1], 64)
			if convErr == nil {
				currentExtInfDuration = duration
			}
		} else if segmentFileRegex.MatchString(line) && currentExtInfDuration != -1 {
			// This line is a segment file name, and we have a pending EXTINF duration
			// The global sequence number of this segment is MEDIA-SEQUENCE + its 0-based index in the playlist
			globalSegmentSeq := latestMediaBase + uint32(segmentIndexInPlaylist)

			// log.Printf("M3U8Monitor: Parsed segment %s, globalSeq: %d (base: %d, index: %d), duration: %.6f", line, globalSegmentSeq, latestMediaBase, segmentIndexInPlaylist, currentExtInfDuration)
			tempDurations[globalSegmentSeq] = currentExtInfDuration

			currentExtInfDuration = -1 // Reset for the next segment
			segmentIndexInPlaylist++
		}

		if err == io.EOF {
			break
		}
	}

	// Merge new findings into the main map
	// This ensures we don't lose old data if the playlist shrinks (e.g. hls_list_size > 0)
	// though for EVENT type with hls_list_size=0, it should only grow.
	if len(tempDurations) > 0 {
		for seq, dur := range tempDurations {
			if _, exists := m.segmentDurations[seq]; !exists {
				log.Printf("M3U8Monitor: Stored duration %.6f for segment %d (playlist: %s)", dur, seq, m.playlistPath)
			}
			m.segmentDurations[seq] = dur
		}
	}
	m.currentMediaBase = latestMediaBase // Update the overall base for next parse
	return nil
}

// GetSegmentDuration retrieves the parsed duration for a given global segment sequence number.
func (m *M3U8Monitor) GetSegmentDuration(globalSeqNum uint32) (float64, bool) {
	// Attempt a parse first, in case fsnotify missed an event or is delayed
	// This adds a bit of latency but increases reliability.
	// Can be made optional if performance becomes an issue.
	// m.parsePlaylist() // Potentially too slow to do on every get. Rely on watcher/polling.

	m.mu.RLock()
	defer m.mu.RUnlock()
	duration, exists := m.segmentDurations[globalSeqNum]
	if exists {
		// log.Printf("M3U8Monitor: Cache HIT for segment %d duration: %.6f", globalSeqNum, duration)
		return duration, true
	}
	// log.Printf("M3U8Monitor: Cache MISS for segment %d duration", globalSeqNum)

	// If not found, try one more explicit parse. This can help if the file was just written.
	// This needs m.mu.Lock(), so we release RLock, get Lock, parse, then re-RLock for read.
	// This is complex. For now, return not found and rely on the background watcher.
	// A more robust solution might involve a brief wait-and-retry here if not found.

	return 0, false
}
